import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'giftCertificate',
  title: 'Gift Certificate',
  type: 'document',
  fields: [
    defineField({ name: 'code', title: 'Code', type: 'string' }),
    defineField({ name: 'amount', title: 'Amount (CAD)', type: 'number' }),
    defineField({ name: 'recipientName', title: 'Recipient Name', type: 'string' }),
    defineField({ name: 'recipientEmail', title: 'Recipient Email', type: 'string' }),
    defineField({ name: 'senderName', title: 'Sender Name', type: 'string' }),
    defineField({ name: 'message', title: 'Personal Message', type: 'text' }),
    defineField({ name: 'purchasedAt', title: 'Purchased At', type: 'datetime' }),
    defineField({ name: 'expiresAt', title: 'Expires At', type: 'datetime' }),
    defineField({ name: 'redeemedAt', title: 'Redeemed At', type: 'datetime' }),
    defineField({ name: 'redeemedBy', title: 'Redeemed By (email)', type: 'string' }),
    defineField({ name: 'stripeSessionId', title: 'Stripe Session ID', type: 'string' }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: {
        list: [
          { title: 'Active', value: 'active' },
          { title: 'Redeemed', value: 'redeemed' },
          { title: 'Expired', value: 'expired' },
          { title: 'Admin Generated', value: 'admin' },
        ],
      },
    }),
    defineField({
      name: 'isAdminGenerated',
      title: 'Admin Generated (Door Prize)',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'remainingBalance',
      title: 'Remaining Balance (CAD)',
      type: 'number',
      description: 'Remaining balance after partial redemptions. Starts equal to amount.',
    }),
    defineField({
      name: 'partialRedemptions',
      title: 'Partial Redemptions',
      type: 'array',
      of: [{
        type: 'object',
        fields: [
          { name: 'redeemedAt',     type: 'datetime', title: 'Redeemed At' },
          { name: 'redeemedBy',     type: 'string',   title: 'Redeemed By (email)' },
          { name: 'amountUsed',     type: 'number',   title: 'Amount Used (CAD)' },
          { name: 'remainingAfter', type: 'number',   title: 'Remaining After' },
          { name: 'workshopName',   type: 'string',   title: 'Workshop' },
        ],
      }],
    }),
    defineField({
      name: 'generatedBy',
      title: 'Generated By',
      type: 'string',
      description: 'Email of the staff member who generated this certificate',
    }),
    defineField({
      name: 'generatedByName',
      title: 'Generated By Name',
      type: 'string',
      description: 'Display name of the staff member who generated this certificate',
    }),
  ],
  preview: {
    select: { code: 'code', amount: 'amount', recipientName: 'recipientName', status: 'status' },
    prepare({ code, amount, recipientName, status }) {
      return {
        title: code ?? 'Gift Certificate',
        subtitle: `$${amount ?? 0} CAD — ${recipientName ?? 'No recipient'} — ${status ?? 'unknown'}`,
      }
    },
  },
})
